# Specific configurations for a Docker environment.
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/boat_rental}  # PostgreSQL Container
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

  # Do not import the .env file - the variables come from the container.

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  secure: true